### PR TITLE
French translation + corrected typo

### PR DESCRIPTION
**Pull request by Facyla**
A missing letter in EN language file + added French translation

### CODE REVIEW

**Comment by mrclay** [comment]
Translation should be added here: https://www.transifex.com/elgg/elgg-mentions/

**Comment by Facyla** [comment]
I use Transifex when available, but i coudn't find any string to translate for this particular project, and could not upload a translated file either as source language is empty. I just send a language request for FR_fr.

**Comment by juho-jaakkola** [comment]
Transifex is unable to read the English translations file because it's still in the Elgg 1.8 syntax that's using `add_translation()`. The file must be updated to return the array. After that the translation can happen at Transifex.

**Comment by juho-jaakkola** [comment]
Fixed in e0f345ec5249475531b16a592487de2fb1854bfe. Let's now give Transifex a couple of days to load the file.

**Pull request closed without merging**
