### PR TITLE
added dutch translation

### PR DESCRIPTION
**Pull request by jeabakker**

### CODE REVIEW

**Comment by ewinslow** [comment]
???? We use Transifex. Please set that up if you want to contribute translations.

**Comment by jeabakker** [comment]
this plugin is not listed in transifex ;)

**Comment by ewinslow** [comment]
So?

**Comment by jeabakker** [comment]
i'm not allowed to add new projects in transifex, so ....

**Comment by ewinslow** [comment]
You can always ask ;)

**Comment by jeabakker** [comment]
see #29

**Comment by juho-jaakkola** [comment]
I merged this because Transifex can't be used for the Elgg 1.8 version. Support for the new translation syntax (returning an array instead of calling ```add_translation()``` wasn't added until 1.9.

**Pull request merged**
